### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by akanksha217** [kartikdurg/Terrible-Thick-Client#2]
Bhai login kaise karte hai tumhare app mein? Itna difficult kyu banaya ki, Registry mein se value mil bhi gaya toh aage kuch nahi kar sakte hum?

Any assistance would be appreciated.

**Comment by kartikdurg** [comment]
You have to develop a decryption logic and its not that difficult. To do that you first have to understand the encryption logic!

Also, Do not close the app. The password for this application changes every time it restarts. :)
